name:                rio-yesod
version:             0.1.0.0
synopsis:            Provide a classy prelude including common Yesod functionality.
github:              commercialhaskell/rio-yesod
author:              Michael Snoyman, Felipe Lessa
maintainer:          michael@snoyman.com
category:            Control, Yesod
license:             MIT
extra-source-files:
- README.md
- ChangeLog.md

description:         See README and Haddocks at <https://www.stackage.org/package/rio-yesod>

dependencies:
- base >= 4.10 && < 10
- rio >= 0.1.8.0
- conduit
- yesod >=1.2
- yesod-newsfeed
- yesod-static
- http-types
- http-conduit
- persistent >=1.1
- aeson
- data-default

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
